# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproto.proto\"\x18\n\x06\x41\x63tion\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x02\"\x07\n\x05\x45mpty\"1\n\x0cStepResponse\x12\x13\n\x0bobservation\x18\x01 \x03(\x02\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x32\x45\n\nGymService\x12\x1e\n\x04Step\x12\x07.Action\x1a\r.StepResponse\x12\x17\n\x05Reset\x12\x06.Empty\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION']._serialized_start=15
  _globals['_ACTION']._serialized_end=39
  _globals['_EMPTY']._serialized_start=41
  _globals['_EMPTY']._serialized_end=48
  _globals['_STEPRESPONSE']._serialized_start=50
  _globals['_STEPRESPONSE']._serialized_end=99
  _globals['_GYMSERVICE']._serialized_start=101
  _globals['_GYMSERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
